# Generated by Django 6.1.1 on 2026-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='objetivos',
            field=models.TextField(default='HEREDAR', help_text='Códigos separados por punto y coma, "todos" o "HEREDAR"'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='ventas_requeridas',
            field=models.CharField(default='HEREDAR', help_text='si, no, indiferente, por_confirmar o HEREDAR', max_length=20),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='objetivos',
            field=models.TextField(blank=True, default='', help_text='Códigos de objetivos cubiertos separados por punto y coma (ej. iniciar_negocio;fortalecer_negocio) o vacío'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='ventas_requeridas',
            field=models.CharField(choices=[('si', 'Sí (exige tener ventas)'), ('no', 'No (exige no tener ventas)'), ('indiferente', 'Indiferente (con o sin ventas)'), ('por_confirmar', 'Por confirmar')], default='por_confirmar', max_length=20, verbose_name='Ventas requeridas'),
        ),
    ]
