# Generated by Django 6.1.1 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0002_convocatoria_objetivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionglobal',
            name='url_retorno_comunidad',
            field=models.URLField(default='https://comunidad.humm.cl', max_length=500, verbose_name='URL de retorno (botón volver)'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada'), ('mixta', 'Mixta'), ('sociedad_civil', 'Sociedad Civil / Fundación'), ('academia', 'Academia / Centro de I+D'), ('regional', 'Regional / Subnacional'), ('otra', 'Otra')], default='publica', max_length=32, verbose_name='Tipo de entidad'),
        ),
    ]
